INSERT INTO `oh_bot_configuration` (`cfg_botid`, `cfg_name`, `cfg_description`, `cfg_value`) VALUES 
('0', 'bot_language', '', 'language.cfg'), 
('0', 'bot_tft', '', '1'), 
('0', 'bot_hostport', '', '6112'), 
('0', 'bot_reconnect', '', '0'), 
('0', 'bot_reconnectport', '', '6114'), 
('0', 'bot_reconnectwaittime', '', '3'), 
('0', 'bot_maxgames', '', '5'), 
('0', 'bot_commandtrigger', '', '!'), 
('0', 'bot_mapcfgpath', '', 'mapcfgs'), 
('0', 'bot_savegamepath', '', 'savegames'), 
('0', 'bot_mappath', '', 'maps'), 
('0', 'bot_savereplays', '', '0'), 
('0', 'bot_replaypath', '', 'replays'), 
('0', 'replay_war3version', '', '24'), 
('0', 'replay_buildnumber', '', '6059'), 
('0', 'bot_virtualhostname', '', '|cFF4080C0GHost'), 
('0', 'bot_hideipaddresses', '', '0'), 
('0', 'bot_checkmultipleipusage', '', '1'), 
('0', 'bot_spoofchecks', '', '´2'), 
('0', 'bot_requirespoofchecks', '', '0'), 
('0', 'bot_reserveadmins', '', '1'), 
('0', 'bot_refreshmessages', '', '0'), 
('0', 'bot_autolock', '', '0'), 
('0', 'bot_autosave', '', '0'), 
('0', 'bot_allowdownloads', '', '1'), 
('0', 'bot_pingduringdownloads', '', '0'), 
('0', 'bot_maxdownloaders', '', '3'), 
('0', 'bot_maxdownloadspeed', '', '0'), 
('0', 'bot_lcpings', '', '1'), 
('0', 'bot_autokickping', '', '400'), 
('0', 'bot_banmethod', '', '1'), 
('0', 'bot_ipblacklistfile', '', '1'), 
('0', 'bot_lobbytimelimit', '', '0'), 
('0', 'bot_latency', '', '100'), 
('0', 'bot_synclimit', '', '50'), 
('0', 'bot_votekickallowed', '', '1'), 
('0', 'bot_votekickpercentage', '', '100'), 
('0', 'bot_defaultmap', '', 'default'), 
('0', 'tcp_nodelay', '', '0'), 
('0', 'bot_matchmakingmethod', '', '1'), 
('0', 'lan_war3version', '', '24'), 
('0', 'udp_broadcasttarget', '', ''), 
('0', 'udp_dontroute', '', '0'), 
('0', 'autohost_maxgames', '', '0'), 
('0', 'autohost_startplayers', '', '0'), 
('0', 'autohost_gamename', '', ''), 
('0', 'autohost_owner ', '', ''), 
('0', 'bnet_server', '', 'europe.battle.net'), 
('0', 'bnet_serveralias', '', 'Europe'), 
('0', 'bnet_cdkeyroc', '', 'FFFFFFFFFFFFFFFFFFFFFFFFFF'), 
('0', 'bnet_cdkeytft', '', 'FFFFFFFFFFFFFFFFFFFFFFFFFF'), 
('0', 'bnet_locale', '', 'system'), 
('0', 'bnet_username', '', ''), 
('0', 'bnet_password', '', ''), 
('0', 'bnet_firstchannel', '', 'The Void'), 
('0', 'bnet_rootadmin', '', ''), 
('0', 'bnet_commandtrigger', '', '.'), 
('0', 'bnet_holdfriends', '', '0'), 
('0', 'bnet_holdclan', '', '0'), 
('0', 'bnet_publiccommands', '', '0'), 
('0', 'bnet_custom_war3version', '', '24'), 
('0', 'bnet_custom_exeversion', '', ''), 
('0', 'bnet_custom_exeversionhashsd', '', ''), 
('0', 'bnet_custom_passwordhashtype', '', ''), 
('0', 'bnet_custom_pvpgnrealmname', '', ''),

('0', 'gameover', '', 'The game was brought you by gamers.host'),
('0', 'gameloaded', '', 'This game is served by gamers.host'),
('0', 'motd', '', 'Welcome to gamers.host');